Repository spacetelescope/drizzle, pull requests merged in 2023-11, with the labels that each got.

#124 Use importlib instead of deprecated pkg_resources
  drizzle/__init__.py
  setup.py
Labels: maintenance

#123 Add Python 3.12 to the test matrix
  .github/workflows/ci.yml
Labels: testing, maintenance

#122 Fix unit test failures with numpy 2.0
  drizzle/tests/test_drizzle.py
Labels: testing, maintenance

#128 Fix devdeps, other updates
  .github/workflows/build.yml
  .github/workflows/ci.yml
  CHANGES.rst
  LICENSE.rst
  MANIFEST.in
  README.rst
  drizzle/tests/test_drizzle.py
  drizzle/tests/test_file_io.py
  drizzle/tests/test_overlap_calc.py
  drizzle/tests/test_pixmap.py
  licenses/README.rst
  pyproject.toml
  setup.py
  tox.ini
Labels: bug, testing, maintenance
