Repository spacetelescope/drizzle, pull requests merged in 2024-02, with the labels that each got.

#135 [SCSB-121] rename `master` -> `main`
  .github/workflows/ci.yml
  README.rst
Labels: maintenance

#137 Fix a bug in pixel inversion routine
  CHANGES.rst
  src/cdrizzlemap.c
Labels: bug

#138 Add unit test for pixel inversion with small image
  drizzle/tests/test_overlap_calc.py
Labels: testing

#140 Deprecate tophat kernel. Warn about flux not being conserved with some kernels
  CHANGES.rst
  drizzle/dodrizzle.py
  drizzle/drizzle.py
  src/cdrizzleapi.c
Labels: bug, documentation

#141 Change warning type for some kernels. Add unit tests for flux conservation
  CHANGES.rst
  drizzle/tests/test_drizzle.py
  src/cdrizzleapi.c
Labels: testing
